- hosts: all

  tasks:
    - name: "Roda: sudo apt update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia
    
    - name: "Instala pacotes em lote"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - 'nginx'
     
    - name: "Alterando o index"
      become: yes
      shell: "echo \"<h1>BEM VINDO A {{inventory_hostname}}<h1> <img src=\"https://tinyurl.com/sv4vna38\">\" > /var/www/html/index.html"

#   - name: What is my inventory_hostname
#     debug: var={{inventory_hostname}}#
#    - name: What is my ansible_hostname
#      debug: var={{ansible_hostname}}
      